### ISSUE TITLE
What is the unit of wavelength?

### ISSUE THREAD

**Issue by ju1987yetchung** [limjoowon/maxwellnet#4]
hello,dear author:
I checked the .json file, the wave length is 1, could you tell me what is its unit? I think maybe it is "meter"(m). But one meter wavelength is not visible light， it is electromagnetic waves. So I think there should be “Dimensionless” process， but I didn't read it in the paper. So could you tell me how you didi "dimensionless"?
Thank you very much.

![image](https://github.com/limjoowon/maxwellnet/assets/115963979/92256482-babb-48b8-8491-26776f647acb)

**Comment by limjoowon** [comment]
Hi, 

It is one micro-meter, you can check the supplementary material.

Best regards,

Joowon
