### ISSUE TITLE
Question about Near2Far Projection

### ISSUE THREAD

**Issue by ASU-ScopeX-Lab** [limjoowon/maxwellnet#5]
In the MaxwellNet paper, the predicted frequency-domain field is projected to far fields using Green's function so the light can focus to a point. Is it the same as Near2Far projection used in FDTD tools? I was wondering whether the codes used to do near2field projection can be released which will be very helpful. Thank you.

**Comment by limjoowon** [comment]
No, I do not know what you mean by the `Near2Far` project, and this is not how I calculated the field. The field outside of the sample can be calculated using `Eq.(2)` in the supplementary material. The method for calculating Green's functions can be found in the following references (as noted in the supplementary material):

_T.-A. Pham, E. Soubies, A. Goy, J. Lim, F. Soulez, D. Psaltis, and M. Unser, “Versatile reconstruction framework for diffraction tomography with intensity measurements and multiple scattering,” Optics Express 26, 2749–2763 (2018)._

Once you have calculated the Green's function in the spatial domain, you can simply convolve it according to `Eq.(2)` in the supplementary material, which will give you the electric field everywhere.
